spring:
  application:
    name: concurrency-test
  
  datasource:
    url: jdbc:h2:tcp://localhost:1521/./concurrency
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      
logging:
  level:
    com.example.concurrency: DEBUG
    org.springframework.transaction: DEBUG
    org.redisson: INFO

server:
  port: 8080